language: php

php:
  - 7.1
  - 7.2
  - 7.4

before_script:
  - composer install

script:
  - vendor/bin/php-cs-fixer fix src --dry-run
  - vendor/bin/phpunit tests --colors --coverage-clover=coverage.xml
